### PR TITLE
plugin-drizzle: fix concurrency issue during initialization

### LINKED ISSUE #140: Bug: Error when starting multiple indexers using `apibara dev`
I have two indexers, one on EVM and another on Starknet. I tried running `apibara dev` which tried to start both indexes and it encountered the below error. 

```shell
> starkpull-indexers@1.0.0 dev /Users/vt/Starkpull/starkpull-indexers
> apibara dev

✔ Output directory .apibara/build cleaned                                                                                                                    apibara 10:59:56 PM
✔ Types written to .apibara/types                                                                                                                            apibara 10:59:56 PM
✔ Indexers built in 3740 ms                                                                                                                                  apibara 11:00:00 PM
✔ Restarting indexers                                                                                                                                        apibara 11:00:00 PM
error DrizzleStorageError: Failed to initialize reorg rollback table
    at initializeReorgRollbackTable (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72712:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72888:9
    ... 5 lines matching cause stack trace ...
    at async Object.callAsync (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:59562:16)
    at async run (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:61721:3) {
  [cause]: error: tuple concurrently updated
      at file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:78133:18
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async initializeReorgRollbackTable (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72686:5)
      at async file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72888:9
      at async file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72469:12
      at async NodePgSession.transaction (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:79423:22)
      at async withTransaction (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72468:10)
      at async file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:72887:7
      at async file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:61724:5
      at async Object.callAsync (file:///Users/vt/Starkpull/starkpull-indexers/.apibara/build/dev.mjs:59562:16) {
    length: 90,
    severity: 'ERROR',
    code: 'XX000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'heapam.c',
    line: '4223',
    routine: 'simple_heap_update'
  }
} 

error Failed to initialize reorg rollback table
```

### PR DESCRIPTION
**Pull request by jaipaljadeja**
Resolves #140 

- adds a `internalContext` plugin for runtime purpose
- adds a `generateIndexerId` util method
- fixes concurrency issue in creation of tables in parallel transactions in drizzle plugin
- updates test and plugins for the above

### CODE REVIEW

File: packages/plugin-drizzle/src/storage.ts [hunk 1]
```diff
@@ -93,18 +117,21 @@ export async function registerTriggers<
...
   endCursor: Cursor,
   idColumn: string,
+  indexerId: string,
 ) {
   try {
     for (const table of tables) {
       await tx.execute(
-        sql.raw(`DROP TRIGGER IF EXISTS ${table}_reorg ON ${table};`),
+        sql.raw(
+          `DROP TRIGGER IF EXISTS ${table}_reorg_${indexerId} ON ${table};`,
```
Comment (fracek) [inline packages/plugin-drizzle/src/storage.ts:126]: We should add an helper function called `triggerName(table, indexerId)` to generate the name.

Comment (fracek) [reply packages/plugin-drizzle/src/storage.ts:126]: Then use the helper function everywhere we need the trigger name.

File: packages/plugin-drizzle/src/storage.ts [hunk 2]
```diff
@@ -45,42 +46,65 @@ export async function initializeReorgRollbackTable<
...
+        CREATE INDEX IF NOT EXISTS idx_reorg_rollback_indexer_id ON __reorg_rollback(indexer_id);
+      `),
+    );
+
+    await tx.execute(
+      sql.raw(`
+        CREATE INDEX IF NOT EXISTS idx_reorg_rollback_cursor ON __reorg_rollback(cursor);
       `),
     );
   } catch (error) {
```
Comment (fracek) [inline packages/plugin-drizzle/src/storage.ts:66]: It should be a composite indexe with both indexer id and cursor in it.

Notice that the query below uses both columns in the same statement.

Comment (fracek) [reply packages/plugin-drizzle/src/storage.ts:66]: Could be that postgres is smart enough to use the two indices for our queries but better not rely on it since we know the queries ahead of time.

**Review by fracek — CHANGES_REQUESTED** [review]

**Review by fracek — APPROVED** [review]
